//Here list some ts constants
export const CANVAS_WIDTH_DEFAULT = 1280
export const CANVAS_HEIGHT_DEFAULT = 640
export const DIALOGUE_X_POS = 320
export const DIALOGUE_Y_POS = 400
export const Text_X_POS = 354
export const TEXT_Y_POS = 504
export const MAX_LINE_LENGTH = 28
export const LINE_SPACING = 40
export const MAX_DIALOGUE_LINES = 4